### PR TITLE
Remove contexture-react

### PR DESCRIPTION
**Pull request by stellarhoof**
### Summary

We moved the contexture-react package to our private monorepo to reduce the burden of maintainability.

### CODE REVIEW

**Comment by JBezerra** [comment]
Yesterday this PR made 1 month of life 🥹 and we still haven't found time to review it.

**Comment by stellarhoof** [comment]
Mostly because it's not very discoverable.

**Review by sandhya-spend — CHANGES_REQUESTED** [review]
There is mention of `contexture-react` in `packages/provider-elasticsearch/README.md` which needs to be removed.

**Review by sandhya-spend — APPROVED** [review]
LGTM.

**Pull request merged**
